### ISSUE TITLE
Gym page 제작 & NotProd Gym 초기화

### ISSUE THREAD

**Issue by CheorHyeon** [SoloForest/TownForest#16]
## Description
Gym 이용권 현황을 보여주는 페이지 view를 제작합니다.
NotProd 파일에 개발환경에 사용할 Gym 정보를 기입합니다.

## TODO
- [ ] Gym page html 제작
- [ ] Gym Controller 제작 -> Url 매핑 기능만
- [ ] NotProd 파일 Gym data 생성

### 기능 
- [ ] HTML 파일만 우선 구현
  - 이용권 현황(00일 남았습니다, 결제일, 시작&종료일 등)를 표시 하기 위한 우선 View만
  - 연장하기/ 일일권구입 / 환불신청(메뉴만 -> 누르면 "관리사무소로 연락 바랍니다" 메세지 출력)
- [ ] NotProd Gym 객체 초기화
### ETC
- HTML 하고 나서, 결제 기능 한번 수업 영상 다시 들은 다음에 기능 구현 할게영

**Comment by elephantLikesApple** [comment]
철현님 체크박스는 괄호 사이를 한 칸 띄워줘야 제대로 표시돼요(속닥속닥)
